package portfolio;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.util.*;
import java.util.concurrent.*;
class EngineTest {
 @Test void duplicateReservationsAndConflictingReplay(){var e=new Engine();var p=Map.<String,Object>of("id","a","sku","BOOK","quantity",2,"version",0);e.command("reserve",p,"learner");e.command("reserve",p,"learner");assertEquals(8,e.state().get("stock"));assertEquals(409,assertThrows(Engine.Problem.class,()->e.command("reserve",Map.of("id","a","sku","BOOK","quantity",3,"version",0),"learner")).status);}
 @Test void concurrentStockCannotGoNegative()throws Exception{var e=new Engine();try(var pool=Executors.newFixedThreadPool(4)){var futures=new ArrayList<Future<Integer>>();for(int i=0;i<10;i++){int id=i;futures.add(pool.submit(()->{try{e.command("reserve",Map.of("id","o"+id,"sku","BOOK","quantity",8,"version",0),"learner");return 200;}catch(Engine.Problem p){return p.status;}}));}int success=0;for(var future:futures)if(future.get()==200)success++;assertEquals(1,success);assertEquals(2,e.state().get("stock"));}}
 @Test void failureRetainsOutboxAndCancelReleasesOnce(){var e=new Engine();e.command("reserve",Map.of("id","a","sku","BOOK","quantity",2,"version",0),"learner");assertThrows(Engine.Problem.class,()->e.command("relay",Map.of("simulateFailure",true),"operator"));assertEquals(1,((List<?>)e.command("relay",Map.of(),"operator").get("delivered")).size());assertEquals(0,((List<?>)e.command("relay",Map.of(),"operator").get("delivered")).size());e.command("cancel",Map.of("id","a","version",0),"operator");e.command("cancel",Map.of("id","a","version",0),"operator");assertEquals(10,e.state().get("stock"));}
 @Test void reviewPermissionsStaleVersionAndScore(){var e=new Engine();e.command("submit",Map.of("id","s","student","S","answers",List.of("transaction","wrong","audit"),"deadline",2000000000),"learner");assertEquals(403,assertThrows(Engine.Problem.class,()->e.command("feedback",Map.of("id","s","version",0,"feedback","Review rubric"),"learner")).status);e.command("feedback",Map.of("id","s","version",0,"feedback","Review rubric"),"instructor");assertThrows(Engine.Problem.class,()->e.command("publish",Map.of("id","s","version",0),"instructor"));assertEquals(2,e.command("publish",Map.of("id","s","version",1),"instructor").get("score"));}
 @Test void gatewayDeadlineContractAndRateLimit(){var e=new Engine();assertEquals(403,assertThrows(Engine.Problem.class,()->e.command("request",Map.of("version","v1","partner","p","simulateDelayMs",0),"learner")).status);assertEquals(422,assertThrows(Engine.Problem.class,()->e.command("request",Map.of("version","v2","partner","p","simulateDelayMs",0),"partner")).status);assertEquals(504,assertThrows(Engine.Problem.class,()->e.command("request",Map.of("version","v1","partner","p","simulateDelayMs",101),"partner")).status);for(int i=0;i<2;i++)e.command("request",Map.of("version","v1","partner","p","simulateDelayMs",0),"partner");assertEquals(429,assertThrows(Engine.Problem.class,()->e.command("request",Map.of("version","v1","partner","p","simulateDelayMs",0),"partner")).status);}
}
